import Head from 'next/head'
import '../app/globals.css'
export default function MyApp({ Component }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content='width=device-width, initial-scale=1' name='viewport' />
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Component />
    </>
  )
}
